flowcell_targets:
    - cutadapt
    - seqtk
    - seqtkplots
    - alignment
    - markdups
    - mosdepth
#  - coverage  # req: alignment
#  - coverage_qc  # req: alignment
#  - kmers

sample_targets:
    - variants
#  - pbsv_vcf  # req: alignment in config['smrtcells_targets']
#  - deepvariant  # req: alignment in config['smrtcells_targets']
#  - whatshap  # req: deepvariant
#  - coverage  # req: whatshapi
#  - kmers  # req: kmers in config['smrtcells_targets']
#  - tandem-genotypes  # req: whatshap

#choose mapping algorithm 'bwa' or 'dragen'
#mapper: 'dragen'
mapper: 'bwa'

#specify sample name
sample: "chm13_subset"

#directory where your data is stored / linked
datadir: "sbb_data"

#adapter sequence for cutadapt
adapter: "ATCGATTCGTGCTCGATGAACCGGGCGCTTA"

#quality score for gatk VariantFiltration
variantfilter: 10.4139
