flowcell_targets:
    - cutadapt
    - seqtk
    - seqtkplots
    - alignment
    - markdups
    - realignment
    - mosdepth
#  - coverage_qc  # req: alignment
#  - kmers

sample_targets:
    - variants
    - updateref
    - filter
    - coverage

#choose mapping algorithm 'bwa' or 'dragen'
#mapper: 'dragen'
mapper: 'bwa'

#specify sample name
sample: "chm13"
ploidy: 1
#directory where your data is stored / linked
datadir: "data"

#adapter sequence for cutadapt
adapter: "ATCGATTCGTGCTCGATGAACCGGGCGCTTA"

#quality score for gatk VariantFiltration
dragenfilter: 10.4139

#filter criteria for BWA
bwafilter: 10

#gatk defaults
minmapq: 60
qdfilter: 11
